version: "2"

linters:
  enable:
    - copyloopvar
    - gocritic
    - gosec
    - lll
    - misspell
    - nakedret
    - unconvert
    - unparam

  settings:
    staticcheck:
      checks:
        - -QF1008

  exclusions:
    generated: lax

formatters:
  enable:
    - gofmt
